import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def send_price_drop_email(to_email, product_name, my_price, competitor_price, platform, url, competitor_name="A competitor"):
    smtp_email = os.environ.get("SMTP_EMAIL")
    smtp_password = os.environ.get("SMTP_PASSWORD")
    
    if not smtp_email or not smtp_password:
        print("SMTP_EMAIL or SMTP_PASSWORD not configured. Skipping email notification.")
        return

    subject = f"🚨 Price Alert: {competitor_name} dropped price for {product_name}"
    
    # Professional HTML Body
    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Inter', Helvetica, Arial, sans-serif; background-color: #f4f4f5; margin: 0; padding: 20px; color: #1f2937; }}
            .container {{ max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); }}
            .header {{ background: linear-gradient(135deg, #4f46e5, #ec4899); padding: 30px 20px; text-align: center; }}
            .header h1 {{ color: #ffffff; margin: 0; font-size: 24px; font-weight: 700; }}
            .content {{ padding: 30px; }}
            .alert-box {{ background: #fee2e2; border-left: 4px solid #ef4444; padding: 15px 20px; border-radius: 4px; margin-bottom: 25px; }}
            .alert-box p {{ margin: 0; color: #991b1b; font-size: 16px; font-weight: 500; }}
            .price-table {{ width: 100%; border-collapse: collapse; margin-bottom: 30px; }}
            .price-table th, .price-table td {{ padding: 15px; text-align: left; border-bottom: 1px solid #e5e7eb; }}
            .price-table th {{ background: #f9fafb; font-weight: 600; color: #4b5563; text-transform: uppercase; font-size: 12px; letter-spacing: 0.05em; }}
            .price-table td {{ font-size: 16px; }}
            .highlight {{ color: #ef4444; font-weight: 700; font-size: 20px; }}
            .btn-container {{ text-align: center; margin-top: 30px; }}
            .btn {{ display: inline-block; background: #4f46e5; color: #ffffff !important; text-decoration: none; padding: 14px 28px; border-radius: 8px; font-weight: 600; font-size: 16px; }}
            .footer {{ background: #f9fafb; padding: 20px; text-align: center; color: #6b7280; font-size: 14px; border-top: 1px solid #e5e7eb; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>Hawkscan Price Intelligence</h1>
            </div>
            <div class="content">
                <div class="alert-box">
                    <p>Alert: {competitor_name} changed their price to {competitor_price} AED.</p>
                </div>
                
                <p style="font-size: 16px; line-height: 1.6; margin-bottom: 25px;">
                    Our 24/7 autonomous monitoring engine has detected a critical market shift. A competitor is currently undercutting your baseline price for <strong>{product_name}</strong> on {platform}.
                </p>

                <table class="price-table">
                    <tr>
                        <th>Your Baseline Price</th>
                        <td><strong>{my_price} AED</strong></td>
                    </tr>
                    <tr>
                        <th>{competitor_name}'s Price</th>
                        <td><span class="highlight">{competitor_price} AED</span></td>
                    </tr>
                    <tr>
                        <th>Difference</th>
                        <td><strong>{round(float(my_price) - float(competitor_price), 2)} AED</strong></td>
                    </tr>
                </table>

                <div class="btn-container">
                    <a href="{url}" class="btn">View Competitor Listing</a>
                </div>
            </div>
            <div class="footer">
                <p>This is an automated alert generated by the Hawkscan AI Engine.<br>Stay ahead of the market.</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    msg = MIMEMultipart('alternative')
    msg['From'] = f"Hawkscan Alerts <{smtp_email}>"
    msg['To'] = to_email
    msg['Subject'] = subject
    
    # Fallback plain text
    plain_text = f"Alert: {competitor_name} changed their price to {competitor_price} AED for {product_name} on {platform}.\nYour Baseline: {my_price} AED\nURL: {url}"
    
    msg.attach(MIMEText(plain_text, 'plain'))
    msg.attach(MIMEText(html_content, 'html'))
    
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(smtp_email, smtp_password)
        server.send_message(msg)
        server.quit()
        print(f"HTML Email notification sent to {to_email} for {product_name}")
    except Exception as e:
        print(f"Failed to send HTML email: {e}")

def send_password_reset_email(to_email, reset_link):
    smtp_email = os.environ.get("SMTP_EMAIL")
    smtp_password = os.environ.get("SMTP_PASSWORD")
    
    if not smtp_email or not smtp_password:
        print("SMTP_EMAIL or SMTP_PASSWORD not configured. Cannot send password reset email.")
        return False

    subject = "Reset Your Hawkscan Password"
    
    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Inter', Helvetica, Arial, sans-serif; background-color: #f4f4f5; margin: 0; padding: 20px; color: #1f2937; }}
            .container {{ max-width: 500px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); padding: 30px; text-align: center; }}
            h2 {{ color: #1f2937; }}
            p {{ font-size: 16px; line-height: 1.5; color: #4b5563; }}
            .btn {{ display: inline-block; background: #4f46e5; color: #ffffff !important; text-decoration: none; padding: 14px 28px; border-radius: 8px; font-weight: 600; font-size: 16px; margin-top: 20px; }}
            .footer {{ margin-top: 30px; color: #9ca3af; font-size: 12px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h2>Password Reset Request</h2>
            <p>We received a request to reset the password for your Hawkscan account associated with this email address.</p>
            <p>Click the button below to choose a new password. This link will expire in 1 hour.</p>
            <a href="{reset_link}" class="btn">Reset Password</a>
            <div class="footer">
                If you didn't request this, you can safely ignore this email.
            </div>
        </div>
    </body>
    </html>
    """
    
    msg = MIMEMultipart('alternative')
    msg['From'] = f"Hawkscan Security <{smtp_email}>"
    msg['To'] = to_email
    msg['Subject'] = subject
    
    plain_text = f"Reset your password by visiting this link: {reset_link}"
    msg.attach(MIMEText(plain_text, 'plain'))
    msg.attach(MIMEText(html_content, 'html'))
    
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(smtp_email, smtp_password)
        server.send_message(msg)
        server.quit()
        print(f"Password reset email sent to {to_email}")
        return True
    except Exception as e:
        print(f"Failed to send password reset email: {e}")
        return False


def send_otp_email(to_email, code):
    import os, smtplib
    from email.mime.text import MIMEText
    from email.mime.multipart import MIMEMultipart
    smtp_email = os.environ.get("SMTP_EMAIL")
    smtp_password = os.environ.get("SMTP_PASSWORD")
    if not smtp_email or not smtp_password:
        print("SMTP_EMAIL or SMTP_PASSWORD not configured. Cannot send OTP email.")
        return False

    subject = "Your Hawkscan Security Code"
    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Inter', Helvetica, Arial, sans-serif; background-color: #f4f4f5; margin: 0; padding: 20px; color: #1f2937; }}
            .container {{ max-width: 500px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); padding: 30px; text-align: center; }}
            h2 {{ color: #1f2937; margin-bottom: 20px; }}
            p {{ font-size: 16px; line-height: 1.5; color: #4b5563; }}
            .code-box {{ background: #f3f4f6; border-radius: 8px; padding: 20px; font-size: 32px; font-weight: 700; letter-spacing: 0.2em; color: #4f46e5; margin: 20px 0; }}
            .footer {{ margin-top: 30px; color: #9ca3af; font-size: 12px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h2>Hawkscan Login Verification</h2>
            <p>Please enter the following 6-digit code to access your account. This code expires in 10 minutes.</p>
            <div class="code-box">{code}</div>
            <div class="footer">If you didn't attempt to log in, please reset your password immediately.</div>
        </div>
    </body>
    </html>
    """
    
    msg = MIMEMultipart('alternative')
    msg['From'] = f"Hawkscan Security <{smtp_email}>"
    msg['To'] = to_email
    msg['Subject'] = subject
    
    msg.attach(MIMEText(f"Your verification code is: {code}", 'plain'))
    msg.attach(MIMEText(html_content, 'html'))
    
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(smtp_email, smtp_password)
        server.send_message(msg)
        server.quit()
        return True
    except Exception as e:
        print(f"Failed to send OTP email: {e}")
        return False
